[colors.primary]
background = "#FFF0F7"
foreground = "#0b9b08"

[colors.normal]
black = "#fbebd4"
red = "#ab0030"
green = "#6d9a23"
yellow = "#e5c600"
#blue = "#41c0e6"
blue = "#00b4e5"
magenta = "#da84b2"
cyan = "#42afc0"
white = "#78593e"

[colors.bright]
black = "#d8c8ae"
red = "#930029"
green = "#5b801f"
yellow = "#f0c674"
blue = "#7cafc2"
magenta = "#da84b2"
cyan = "#85d3ce"
white = "#634933"

